In [2]:
import pandas as pd

df = pd.read_excel('Cleaned_S&P_500_Composition_Changes.xlsx', sheetname=4)

In [4]:
df.rows.count()

AttributeError: 'DataFrame' object has no attribute 'rows'

In [3]:
labels = df.columns.tolist()[0:2]
dates = df.columns.tolist()[2:]

dates = [date.strftime("%Y-%m-%d %H:%M:%S")[0:10] for date in dates]
df.columns = labels + dates

In [4]:
df.head()

,Ticker,Name,2016-12-31,2016-11-30,2016-10-31,2016-09-30,2016-08-31,2016-07-31,2016-06-30,2016-03-31,...,1972-06-30,1972-03-31,1971-12-31,1971-09-30,1971-06-30,1971-03-31,1970-12-31,1970-09-30,1970-06-30,1970-03-31
0,A,Agilent Technologies Inc.,Health Care,Health Care,Health Care,Health Care,Health Care,Health Care,Health Care,Health Care,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A (Anaco),Anaconda Co,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials
2,AA,Alcoa Inc,NaN,NaN,Materials,Materials,Materials,Materials,Materials,Materials,...,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials
3,AAF,American Air Filter Inc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AAL,American Airlines Group,Industrials,Industrials,Industrials,Industrials,Industrials,Industrials,Industrials,Industrials,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Get all the companies that were in the index at a given date
companies_end_of_2016 = df[["Name", "2016-12-31"]].dropna()
companies_end_of_2016

                                  Name              2016-12-31
0            Agilent Technologies Inc.             Health Care
4              American Airlines Group             Industrials
6               Advance Auto Parts Inc  Consumer Discretionary
7                           Apple Inc.  Information Technology
9                          AbbVie Inc.             Health Care
10             AmerisourceBergen Corp.             Health Care
15                 Abbott Laboratories             Health Care
20                       Accenture plc  Information Technology
28                  Adobe Systems Inc.  Information Technology
30                 Analog Devices Inc.  Information Technology
32          Archer-Daniels-Midland Co.        Consumer Staples
33                           ADP, LLC.  Information Technology
35         Alliance Data Systems Corp.  Information Technology
36                       Autodesk Inc.  Information Technology
38                        Ameren Corp.               Utilities
39             American Electric Power               Utilities
40                           AES Corp.               Utilities
41                          Aetna Inc.             Health Care
43                          AFLAC Inc.              Financials
48                       Allergan, Plc             Health Care
54                           AIG, Inc.              Financials
57                               Aimco             Real Estate
58                       Assurant Inc.              Financials
59            Arthur J. Gallagher & Co              Financials
60            Akamai Technologies Inc.  Information Technology
63                Alaska Air Group Inc             Industrials
64                      Allstate Corp.              Financials
65                            Allegion             Industrials
68             Alexion Pharmaceuticals             Health Care
71              Applied Materials Inc.  Information Technology
...                                ...                     ...
1479                Williams Companies                  Energy
1480                   Wal-Mart Stores        Consumer Staples
1487                       WestRock Co               Materials
1491                 Western Union Co.  Information Technology
1494                Weyerhaeuser Corp.             Real Estate
1496                 Wyndham Worldwide  Consumer Discretionary
1497                 Wynn Resorts Ltd.  Consumer Discretionary
1500                    Cimarex Energy                  Energy
1501                  Xcel Energy Inc.               Utilities
1502                        XL Capital              Financials
1503                       Xilinx Inc.  Information Technology
1505                 Exxon Mobil Corp.                  Energy
1506                    Dentsply Int'l             Health Care
1507                       Xerox Corp.  Information Technology
1509                        Xylem Inc.             Industrials
1510                        Yahoo Inc.  Information Technology
1513                  Yum! Brands Inc.  Consumer Discretionary
1516            Zimmer Biomet Holdings             Health Care
1518                     Zions Bancorp              Financials
1520                      Zoetis, Inc.             Health Care
1521              The Cooper Companies             Health Care
1522            Charter Communications  Consumer Discretionary
1523                    Mettler Toledo             Health Care
1524                      Fortive Corp             Industrials
1525               Alliant Energy Corp               Utilities
1526                    Albemarle Corp               Materials
1527                          Coty Inc        Consumer Staples
1528  Mid-America Apartment Commu. Inc             Real Estate
1529          Envision Healthcare Corp             Health Care
1530                       Arconic Inc             Industrials

[505 rows x 2 columns]

In [8]:
df["industry"] = df["2016-12-31"]
# def aggregate_industries(row):
#     date_columns = df.columns.tolist()[2:]
#     print(date_columns)
#     print[row[[date_columns]]
# #     set(row[[date_columns]].tolist())

# df.loc[2]
    
# df["industry"] = df.apply(lambda row: aggregate_industries(row), axis=1)

In [9]:
df.head()

,Ticker,Name,2016-12-31,2016-11-30,2016-10-31,2016-09-30,2016-08-31,2016-07-31,2016-06-30,2016-03-31,...,1972-03-31,1971-12-31,1971-09-30,1971-06-30,1971-03-31,1970-12-31,1970-09-30,1970-06-30,1970-03-31,industry
0,A,Agilent Technologies Inc.,Health Care,Health Care,Health Care,Health Care,Health Care,Health Care,Health Care,Health Care,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Health Care
1,A (Anaco),Anaconda Co,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials,NaN
2,AA,Alcoa Inc,NaN,NaN,Materials,Materials,Materials,Materials,Materials,Materials,...,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials,Materials,NaN
3,AAF,American Air Filter Inc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AAL,American Airlines Group,Industrials,Industrials,Industrials,Industrials,Industrials,Industrials,Industrials,Industrials,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Industrials